version: 2

sources:
  - name: raw_data
    database:  Final_project
    schema: starschema            
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: products